add Kakarot zkEVM project
jmcph4/awesome-reth pull request #3
Opened 2024-06-12 16:38 UTC by tcoratger

For more information, see:
- Website: https://www.kakarot.org/
- Doc: https://docs.kakarot.org/

2024-06-12 21:48 UTC, jmcph4 requested changes
I had no idea Kakarot was using Reth!

2024-06-12 21:48 UTC, jmcph4 commented on README.md
> + - [Kakarot zkEVM](https://github.com/kkrt-labs), a zkEVM built in Cairo (provable by design) for which the [RPC](https://github.com/kkrt-labs/kakarot-rpc) is constructed using Reth.
```suggestion
 - [Kakarot zkEVM](https://github.com/kkrt-labs/kakarot-rpc), a zkEVM built in Cairo (provable by design) for which the RPC component is constructed using Reth
```

2024-06-27 10:09 UTC, tcoratger commented
Hey @jmcph4 anything I can do here to merge?

2024-06-30 03:28 UTC, merged

2024-06-30 03:29 UTC, jmcph4 commented
> Hey @jmcph4 anything I can do here to merge?

Done. Thanks for the contribution!